### ISSUE TITLE
Pangea blockchain mainnet launch

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Integration#165]
Acceptance criteria

- [ ] domains updated in settings
- [ ] launch
- [ ] check all working
- [ ] update links in developer docs and integration repository

How to setup node:
1. Create new Hetzner CPX31 resource
2. setup the Ansible repository by pointing network `pangea1_mainnet` network and host `pangea1_mainnet.primary` to the new server
3. Run the playbook to install Antelope on the server
4. Follow the bootstrapping instructions below to start a fresh chain from genesis:
  - https://gitlab.com/advantaproductions/ansible/-/blob/master/roles/tasks/files/scripts/tasks_helpers.sh?ref_type=heads#L223
  - https://gitlab.com/advantaproductions/ansible/-/blob/master/roles/tasks/files/scripts/tasks_helpers.sh?ref_type=heads#L271

**Comment by theblockstalk** [comment]
fix and merge to master: https://github.com/Tonomy-Foundation/Block-Explorer/pull/11

**Comment by sadiabbasi** [comment]
https://docs.google.com/document/d/1N5DIEQznxThzNCrQVNIU47BATk2XtNg8zjGiHoerQsw/edit#heading=h.s01neeqkkda8
