### ISSUE TITLE
Create username - integration test

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Integration#29]
**User story**

As a new user
I can create a new account with a new strong password
So that I can use Telos ID

**Definition of done**

- [x] Choose a typescript based framework for writing integration tests **(1.)**
- [x] When `./app.sh test` is run, a test is run that covers the SDK logic to create and save a new account **(2.)(3.)**

**Hints**

1. Viable options

- jasmine
- jest
- mokka
- https://nodejs.org/api/test.html

Requirements

- We will need to be able to run this in Jenkins, maybe in a docker container
- the suite will run alongside other docker containers (for the eosio nodes)

2. `app.sh test` should first run the `init` bash function to create a new, reset blockchain node to test with
3. We may need to write some intial logic in bash and/or typescript that will initialize some blockchain state to create accounts with

**Comment by theblockstalk** [comment]
Code created but not tested yet. Can be used for test driven develpment

**Comment by kamitor** [comment]
Blocked on technical issue for EOSIO
